// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2LwFKXkszdivKjQYQPnuZOeP66Y9LJo',
    appId: '1:20493783398:web:2d7492bee83d69070f78a7',
    messagingSenderId: '20493783398',
    projectId: 'france-demarches-1d745',
    authDomain: 'france-demarches-1d745.firebaseapp.com',
    storageBucket: 'france-demarches-1d745.firebasestorage.app',
    measurementId: 'G-FDSXD3DJX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWsnrnBqyWqOTAIiU1Fc8N6rtwmrE6gs',
    appId: '1:20493783398:android:1746dc902766b0a30f78a7',
    messagingSenderId: '20493783398',
    projectId: 'france-demarches-1d745',
    storageBucket: 'france-demarches-1d745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQANvtCdjj3u9Hp3q5G67pRgxGMKvvS90',
    appId: '1:20493783398:ios:38f7216a8d3cf2570f78a7',
    messagingSenderId: '20493783398',
    projectId: 'france-demarches-1d745',
    storageBucket: 'france-demarches-1d745.firebasestorage.app',
    iosClientId: '20493783398-a21v8mc40tju6ds8a5f2r7qqgjmpphu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.demarchesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQANvtCdjj3u9Hp3q5G67pRgxGMKvvS90',
    appId: '1:20493783398:ios:38f7216a8d3cf2570f78a7',
    messagingSenderId: '20493783398',
    projectId: 'france-demarches-1d745',
    storageBucket: 'france-demarches-1d745.firebasestorage.app',
    iosClientId: '20493783398-a21v8mc40tju6ds8a5f2r7qqgjmpphu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.demarchesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk2LwFKXkszdivKjQYQPnuZOeP66Y9LJo',
    appId: '1:20493783398:web:a8856857a61187260f78a7',
    messagingSenderId: '20493783398',
    projectId: 'france-demarches-1d745',
    authDomain: 'france-demarches-1d745.firebaseapp.com',
    storageBucket: 'france-demarches-1d745.firebasestorage.app',
    measurementId: 'G-JLTZ08JFCD',
  );
}
